//
// CreateIntegration200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.CreateIntegration200Response")
public typealias CreateIntegration200Response = kandji_sdkAPI.CreateIntegration200Response

extension kandji_sdkAPI {

@objcMembers public class CreateIntegration200Response: NSObject, Codable, JSONEncodable {

    public var _id: String?
    public var blueprint: CreateIntegration200ResponseBlueprint?
    public var accessTokenExpiry: String?
    public var serverName: String?
    public var serverUuid: String?
    public var adminId: String?
    public var orgName: String?
    public var orgEmail: String?
    public var orgPhone: String?
    public var orgAddress: String?
    public var orgType: String?
    public var stokenFileName: String?
    public var lastDeviceSync: AnyCodable?
    public var defaults: CreateIntegration200ResponseDefaults?
    public var daysLeft: Int?
    public var daysLeftNum: NSNumber? {
        get {
            return daysLeft as NSNumber?
        }
    }
    public var status: String?
    public var statusReason: AnyCodable?
    public var statusReceivedAt: AnyCodable?
    public var deviceCounts: CreateIntegration200ResponseDeviceCounts?

    public init(_id: String? = nil, blueprint: CreateIntegration200ResponseBlueprint? = nil, accessTokenExpiry: String? = nil, serverName: String? = nil, serverUuid: String? = nil, adminId: String? = nil, orgName: String? = nil, orgEmail: String? = nil, orgPhone: String? = nil, orgAddress: String? = nil, orgType: String? = nil, stokenFileName: String? = nil, lastDeviceSync: AnyCodable? = nil, defaults: CreateIntegration200ResponseDefaults? = nil, daysLeft: Int? = nil, status: String? = nil, statusReason: AnyCodable? = nil, statusReceivedAt: AnyCodable? = nil, deviceCounts: CreateIntegration200ResponseDeviceCounts? = nil) {
        self._id = _id
        self.blueprint = blueprint
        self.accessTokenExpiry = accessTokenExpiry
        self.serverName = serverName
        self.serverUuid = serverUuid
        self.adminId = adminId
        self.orgName = orgName
        self.orgEmail = orgEmail
        self.orgPhone = orgPhone
        self.orgAddress = orgAddress
        self.orgType = orgType
        self.stokenFileName = stokenFileName
        self.lastDeviceSync = lastDeviceSync
        self.defaults = defaults
        self.daysLeft = daysLeft
        self.status = status
        self.statusReason = statusReason
        self.statusReceivedAt = statusReceivedAt
        self.deviceCounts = deviceCounts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case blueprint
        case accessTokenExpiry = "access_token_expiry"
        case serverName = "server_name"
        case serverUuid = "server_uuid"
        case adminId = "admin_id"
        case orgName = "org_name"
        case orgEmail = "org_email"
        case orgPhone = "org_phone"
        case orgAddress = "org_address"
        case orgType = "org_type"
        case stokenFileName = "stoken_file_name"
        case lastDeviceSync = "last_device_sync"
        case defaults
        case daysLeft = "days_left"
        case status
        case statusReason = "status_reason"
        case statusReceivedAt = "status_received_at"
        case deviceCounts = "device_counts"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_id, forKey: ._id)
        try container.encodeIfPresent(blueprint, forKey: .blueprint)
        try container.encodeIfPresent(accessTokenExpiry, forKey: .accessTokenExpiry)
        try container.encodeIfPresent(serverName, forKey: .serverName)
        try container.encodeIfPresent(serverUuid, forKey: .serverUuid)
        try container.encodeIfPresent(adminId, forKey: .adminId)
        try container.encodeIfPresent(orgName, forKey: .orgName)
        try container.encodeIfPresent(orgEmail, forKey: .orgEmail)
        try container.encodeIfPresent(orgPhone, forKey: .orgPhone)
        try container.encodeIfPresent(orgAddress, forKey: .orgAddress)
        try container.encodeIfPresent(orgType, forKey: .orgType)
        try container.encodeIfPresent(stokenFileName, forKey: .stokenFileName)
        try container.encodeIfPresent(lastDeviceSync, forKey: .lastDeviceSync)
        try container.encodeIfPresent(defaults, forKey: .defaults)
        try container.encodeIfPresent(daysLeft, forKey: .daysLeft)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(statusReason, forKey: .statusReason)
        try container.encodeIfPresent(statusReceivedAt, forKey: .statusReceivedAt)
        try container.encodeIfPresent(deviceCounts, forKey: .deviceCounts)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension kandji_sdkAPI.CreateIntegration200Response: Identifiable {}
