//
// DeviceInformationGetDeviceActivity200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.DeviceInformationGetDeviceActivity200Response")
public typealias DeviceInformationGetDeviceActivity200Response = kandji_sdkAPI.DeviceInformationGetDeviceActivity200Response

extension kandji_sdkAPI {

@objcMembers public class DeviceInformationGetDeviceActivity200Response: NSObject, Codable, JSONEncodable {

    public var activity: BlueprintsListBlueprints200Response?
    public var deviceId: String?

    public init(activity: BlueprintsListBlueprints200Response? = nil, deviceId: String? = nil) {
        self.activity = activity
        self.deviceId = deviceId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activity
        case deviceId = "device_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(activity, forKey: .activity)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
    }
}

}
