//
// DeviceInformationGetDeviceDetails200ResponseManagement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.DeviceInformationGetDeviceDetails200ResponseManagement")
public typealias DeviceInformationGetDeviceDetails200ResponseManagement = kandji_sdkAPI.DeviceInformationGetDeviceDetails200ResponseManagement

extension kandji_sdkAPI {

@objcMembers public class DeviceInformationGetDeviceDetails200ResponseManagement: NSObject, Codable, JSONEncodable {

    public var managementMode: String?
    public var ownership: String?

    public init(managementMode: String? = nil, ownership: String? = nil) {
        self.managementMode = managementMode
        self.ownership = ownership
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case managementMode = "management_mode"
        case ownership
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(managementMode, forKey: .managementMode)
        try container.encodeIfPresent(ownership, forKey: .ownership)
    }
}

}
