//
// DeviceInformationGetDeviceDetails200ResponseMdm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.DeviceInformationGetDeviceDetails200ResponseMdm")
public typealias DeviceInformationGetDeviceDetails200ResponseMdm = kandji_sdkAPI.DeviceInformationGetDeviceDetails200ResponseMdm

extension kandji_sdkAPI {

@objcMembers public class DeviceInformationGetDeviceDetails200ResponseMdm: NSObject, Codable, JSONEncodable {

    public var mdmEnabled: String?
    public var supervised: String?
    public var installDate: String?
    public var lastCheckIn: String?
    public var mdmEnabledUser: AnyCodable?

    public init(mdmEnabled: String? = nil, supervised: String? = nil, installDate: String? = nil, lastCheckIn: String? = nil, mdmEnabledUser: AnyCodable? = nil) {
        self.mdmEnabled = mdmEnabled
        self.supervised = supervised
        self.installDate = installDate
        self.lastCheckIn = lastCheckIn
        self.mdmEnabledUser = mdmEnabledUser
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mdmEnabled = "mdm_enabled"
        case supervised
        case installDate = "install_date"
        case lastCheckIn = "last_check_in"
        case mdmEnabledUser = "mdm_enabled_user"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mdmEnabled, forKey: .mdmEnabled)
        try container.encodeIfPresent(supervised, forKey: .supervised)
        try container.encodeIfPresent(installDate, forKey: .installDate)
        try container.encodeIfPresent(lastCheckIn, forKey: .lastCheckIn)
        try container.encodeIfPresent(mdmEnabledUser, forKey: .mdmEnabledUser)
    }
}

}
