//
// DeviceInformationGetDeviceDetails200ResponseHardwareOverview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.DeviceInformationGetDeviceDetails200ResponseHardwareOverview")
public typealias DeviceInformationGetDeviceDetails200ResponseHardwareOverview = kandji_sdkAPI.DeviceInformationGetDeviceDetails200ResponseHardwareOverview

extension kandji_sdkAPI {

@objcMembers public class DeviceInformationGetDeviceDetails200ResponseHardwareOverview: NSObject, Codable, JSONEncodable {

    public var uuid: String?
    public var serialNumber: String?
    public var modelIdentifier: String?

    public init(uuid: String? = nil, serialNumber: String? = nil, modelIdentifier: String? = nil) {
        self.uuid = uuid
        self.serialNumber = serialNumber
        self.modelIdentifier = modelIdentifier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case uuid
        case serialNumber = "serial_number"
        case modelIdentifier = "model_identifier"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(serialNumber, forKey: .serialNumber)
        try container.encodeIfPresent(modelIdentifier, forKey: .modelIdentifier)
    }
}

}
