//
// DeviceInformationGetDeviceDetails200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.DeviceInformationGetDeviceDetails200Response")
public typealias DeviceInformationGetDeviceDetails200Response = kandji_sdkAPI.DeviceInformationGetDeviceDetails200Response

extension kandji_sdkAPI {

@objcMembers public class DeviceInformationGetDeviceDetails200Response: NSObject, Codable, JSONEncodable {

    public var general: DeviceInformationGetDeviceDetails200ResponseGeneral?
    public var mdm: DeviceInformationGetDeviceDetails200ResponseMdm?
    public var activationLock: DeviceInformationGetDeviceDetails200ResponseActivationLock?
    public var filevault: DeviceInformationGetDeviceDetails200ResponseFilevault?
    public var lostMode: DeviceInformationGetDeviceDetails200ResponseLostMode?
    public var automatedDeviceEnrollment: DeviceInformationGetDeviceDetails200ResponseAutomatedDeviceEnrollment?
    public var kandjiAgent: DeviceInformationGetDeviceDetails200ResponseKandjiAgent?
    public var hardwareOverview: DeviceInformationGetDeviceDetails200ResponseHardwareOverview?
    public var volumes: AnyCodable?
    public var network: AnyCodable?
    public var recoveryInformation: DeviceInformationGetDeviceDetails200ResponseRecoveryInformation?
    public var users: DeviceInformationGetDeviceDetails200ResponseUsers?
    public var installedProfiles: AnyCodable?
    public var appleBusinessManager: DeviceInformationGetDeviceDetails200ResponseAppleBusinessManager?
    public var securityInformation: DeviceInformationGetDeviceDetails200ResponseSecurityInformation?
    public var cellular: DeviceInformationGetDeviceDetails200ResponseCellular?
    public var tags: AnyCodable?

    public init(general: DeviceInformationGetDeviceDetails200ResponseGeneral? = nil, mdm: DeviceInformationGetDeviceDetails200ResponseMdm? = nil, activationLock: DeviceInformationGetDeviceDetails200ResponseActivationLock? = nil, filevault: DeviceInformationGetDeviceDetails200ResponseFilevault? = nil, lostMode: DeviceInformationGetDeviceDetails200ResponseLostMode? = nil, automatedDeviceEnrollment: DeviceInformationGetDeviceDetails200ResponseAutomatedDeviceEnrollment? = nil, kandjiAgent: DeviceInformationGetDeviceDetails200ResponseKandjiAgent? = nil, hardwareOverview: DeviceInformationGetDeviceDetails200ResponseHardwareOverview? = nil, volumes: AnyCodable? = nil, network: AnyCodable? = nil, recoveryInformation: DeviceInformationGetDeviceDetails200ResponseRecoveryInformation? = nil, users: DeviceInformationGetDeviceDetails200ResponseUsers? = nil, installedProfiles: AnyCodable? = nil, appleBusinessManager: DeviceInformationGetDeviceDetails200ResponseAppleBusinessManager? = nil, securityInformation: DeviceInformationGetDeviceDetails200ResponseSecurityInformation? = nil, cellular: DeviceInformationGetDeviceDetails200ResponseCellular? = nil, tags: AnyCodable? = nil) {
        self.general = general
        self.mdm = mdm
        self.activationLock = activationLock
        self.filevault = filevault
        self.lostMode = lostMode
        self.automatedDeviceEnrollment = automatedDeviceEnrollment
        self.kandjiAgent = kandjiAgent
        self.hardwareOverview = hardwareOverview
        self.volumes = volumes
        self.network = network
        self.recoveryInformation = recoveryInformation
        self.users = users
        self.installedProfiles = installedProfiles
        self.appleBusinessManager = appleBusinessManager
        self.securityInformation = securityInformation
        self.cellular = cellular
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case general
        case mdm
        case activationLock = "activation_lock"
        case filevault
        case lostMode = "lost_mode"
        case automatedDeviceEnrollment = "automated_device_enrollment"
        case kandjiAgent = "kandji_agent"
        case hardwareOverview = "hardware_overview"
        case volumes
        case network
        case recoveryInformation = "recovery_information"
        case users
        case installedProfiles = "installed_profiles"
        case appleBusinessManager = "apple_business_manager"
        case securityInformation = "security_information"
        case cellular
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(general, forKey: .general)
        try container.encodeIfPresent(mdm, forKey: .mdm)
        try container.encodeIfPresent(activationLock, forKey: .activationLock)
        try container.encodeIfPresent(filevault, forKey: .filevault)
        try container.encodeIfPresent(lostMode, forKey: .lostMode)
        try container.encodeIfPresent(automatedDeviceEnrollment, forKey: .automatedDeviceEnrollment)
        try container.encodeIfPresent(kandjiAgent, forKey: .kandjiAgent)
        try container.encodeIfPresent(hardwareOverview, forKey: .hardwareOverview)
        try container.encodeIfPresent(volumes, forKey: .volumes)
        try container.encodeIfPresent(network, forKey: .network)
        try container.encodeIfPresent(recoveryInformation, forKey: .recoveryInformation)
        try container.encodeIfPresent(users, forKey: .users)
        try container.encodeIfPresent(installedProfiles, forKey: .installedProfiles)
        try container.encodeIfPresent(appleBusinessManager, forKey: .appleBusinessManager)
        try container.encodeIfPresent(securityInformation, forKey: .securityInformation)
        try container.encodeIfPresent(cellular, forKey: .cellular)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

}
