//
// DeviceInformationGetDeviceDetails200ResponseActivationLock.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.DeviceInformationGetDeviceDetails200ResponseActivationLock")
public typealias DeviceInformationGetDeviceDetails200ResponseActivationLock = kandji_sdkAPI.DeviceInformationGetDeviceDetails200ResponseActivationLock

extension kandji_sdkAPI {

@objcMembers public class DeviceInformationGetDeviceDetails200ResponseActivationLock: NSObject, Codable, JSONEncodable {

    public var activationLockAllowedWhileSupervised: Int?
    public var activationLockAllowedWhileSupervisedNum: NSNumber? {
        get {
            return activationLockAllowedWhileSupervised as NSNumber?
        }
    }
    public var activationLockSupported: Int?
    public var activationLockSupportedNum: NSNumber? {
        get {
            return activationLockSupported as NSNumber?
        }
    }
    public var bypassCodeFailed: Int?
    public var bypassCodeFailedNum: NSNumber? {
        get {
            return bypassCodeFailed as NSNumber?
        }
    }
    public var deviceActivationLockEnabled: Int?
    public var deviceActivationLockEnabledNum: NSNumber? {
        get {
            return deviceActivationLockEnabled as NSNumber?
        }
    }
    public var userActivationLockEnabled: Int?
    public var userActivationLockEnabledNum: NSNumber? {
        get {
            return userActivationLockEnabled as NSNumber?
        }
    }

    public init(activationLockAllowedWhileSupervised: Int? = nil, activationLockSupported: Int? = nil, bypassCodeFailed: Int? = nil, deviceActivationLockEnabled: Int? = nil, userActivationLockEnabled: Int? = nil) {
        self.activationLockAllowedWhileSupervised = activationLockAllowedWhileSupervised
        self.activationLockSupported = activationLockSupported
        self.bypassCodeFailed = bypassCodeFailed
        self.deviceActivationLockEnabled = deviceActivationLockEnabled
        self.userActivationLockEnabled = userActivationLockEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case activationLockAllowedWhileSupervised = "activation_lock_allowed_while_supervised"
        case activationLockSupported = "activation_lock_supported"
        case bypassCodeFailed = "bypass_code_failed"
        case deviceActivationLockEnabled = "device_activation_lock_enabled"
        case userActivationLockEnabled = "user_activation_lock_enabled"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(activationLockAllowedWhileSupervised, forKey: .activationLockAllowedWhileSupervised)
        try container.encodeIfPresent(activationLockSupported, forKey: .activationLockSupported)
        try container.encodeIfPresent(bypassCodeFailed, forKey: .bypassCodeFailed)
        try container.encodeIfPresent(deviceActivationLockEnabled, forKey: .deviceActivationLockEnabled)
        try container.encodeIfPresent(userActivationLockEnabled, forKey: .userActivationLockEnabled)
    }
}

}
