//
// DeviceInformationGetDeviceDetails200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.DeviceInformationGetDeviceDetails200Response")
public typealias DeviceInformationGetDeviceDetails200Response = kandji_sdkAPI.DeviceInformationGetDeviceDetails200Response

extension kandji_sdkAPI {

@objcMembers public class DeviceInformationGetDeviceDetails200Response: NSObject, Codable, JSONEncodable {

    public var cellular: DeviceInformationGetDeviceDetails200ResponseCellular?
    public var general: DeviceInformationGetDeviceDetails200ResponseGeneral?
    public var hardware: DeviceInformationGetDeviceDetails200ResponseHardware?
    public var management: DeviceInformationGetDeviceDetails200ResponseManagement?
    public var security: DeviceInformationGetDeviceDetails200ResponseSecurity?
    public var tags: AnyCodable?

    public init(cellular: DeviceInformationGetDeviceDetails200ResponseCellular? = nil, general: DeviceInformationGetDeviceDetails200ResponseGeneral? = nil, hardware: DeviceInformationGetDeviceDetails200ResponseHardware? = nil, management: DeviceInformationGetDeviceDetails200ResponseManagement? = nil, security: DeviceInformationGetDeviceDetails200ResponseSecurity? = nil, tags: AnyCodable? = nil) {
        self.cellular = cellular
        self.general = general
        self.hardware = hardware
        self.management = management
        self.security = security
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cellular
        case general
        case hardware
        case management
        case security
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cellular, forKey: .cellular)
        try container.encodeIfPresent(general, forKey: .general)
        try container.encodeIfPresent(hardware, forKey: .hardware)
        try container.encodeIfPresent(management, forKey: .management)
        try container.encodeIfPresent(security, forKey: .security)
        try container.encodeIfPresent(tags, forKey: .tags)
    }
}

}
