//
// InlineObject27Args.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.InlineObject27Args")
public typealias InlineObject27Args = kandji_sdkAPI.InlineObject27Args

extension kandji_sdkAPI {

@objcMembers public class InlineObject27Args: NSObject, Codable, JSONEncodable {

    public var filter: AnyCodable?
    public var columns: AnyCodable?
    public var sortBy: String?
    public var blueprintIds: AnyCodable?
    public var deviceFamilies: AnyCodable?

    public init(filter: AnyCodable? = nil, columns: AnyCodable? = nil, sortBy: String? = nil, blueprintIds: AnyCodable? = nil, deviceFamilies: AnyCodable? = nil) {
        self.filter = filter
        self.columns = columns
        self.sortBy = sortBy
        self.blueprintIds = blueprintIds
        self.deviceFamilies = deviceFamilies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filter
        case columns
        case sortBy = "sort_by"
        case blueprintIds = "blueprint_ids"
        case deviceFamilies = "device_families"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filter, forKey: .filter)
        try container.encodeIfPresent(columns, forKey: .columns)
        try container.encodeIfPresent(sortBy, forKey: .sortBy)
        try container.encodeIfPresent(blueprintIds, forKey: .blueprintIds)
        try container.encodeIfPresent(deviceFamilies, forKey: .deviceFamilies)
    }
}

}
