//
// InlineObject37Integration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.InlineObject37Integration")
public typealias InlineObject37Integration = kandji_sdkAPI.InlineObject37Integration

extension kandji_sdkAPI {

@objcMembers public class InlineObject37Integration: NSObject, Codable, JSONEncodable {

    public var _id: Int?
    public var _idNum: NSNumber? {
        get {
            return _id as NSNumber?
        }
    }
    public var name: String?
    public var uuid: String?
    public var type: String?

    public init(_id: Int? = nil, name: String? = nil, uuid: String? = nil, type: String? = nil) {
        self._id = _id
        self.name = name
        self.uuid = uuid
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case name
        case uuid
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_id, forKey: ._id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(uuid, forKey: .uuid)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension kandji_sdkAPI.InlineObject37Integration: Identifiable {}
