//
// InlineObject10LostModeLastLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.InlineObject10LostModeLastLocation")
public typealias InlineObject10LostModeLastLocation = kandji_sdkAPI.InlineObject10LostModeLastLocation

extension kandji_sdkAPI {

@objcMembers public class InlineObject10LostModeLastLocation: NSObject, Codable, JSONEncodable {

    public var latitude: String?
    public var longitude: String?

    public init(latitude: String? = nil, longitude: String? = nil) {
        self.latitude = latitude
        self.longitude = longitude
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case latitude
        case longitude
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(longitude, forKey: .longitude)
    }
}

}
