//
// InlineObject10KandjiAgent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.InlineObject10KandjiAgent")
public typealias InlineObject10KandjiAgent = kandji_sdkAPI.InlineObject10KandjiAgent

extension kandji_sdkAPI {

@objcMembers public class InlineObject10KandjiAgent: NSObject, Codable, JSONEncodable {

    public var agentInstalled: String?
    public var installDate: String?
    public var lastCheckIn: String?
    public var agentVersion: String?

    public init(agentInstalled: String? = nil, installDate: String? = nil, lastCheckIn: String? = nil, agentVersion: String? = nil) {
        self.agentInstalled = agentInstalled
        self.installDate = installDate
        self.lastCheckIn = lastCheckIn
        self.agentVersion = agentVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case agentInstalled = "agent_installed"
        case installDate = "install_date"
        case lastCheckIn = "last_check_in"
        case agentVersion = "agent_version"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(agentInstalled, forKey: .agentInstalled)
        try container.encodeIfPresent(installDate, forKey: .installDate)
        try container.encodeIfPresent(lastCheckIn, forKey: .lastCheckIn)
        try container.encodeIfPresent(agentVersion, forKey: .agentVersion)
    }
}

}
