//
// InlineObjectDeviceCounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.InlineObjectDeviceCounts")
public typealias InlineObjectDeviceCounts = kandji_sdkAPI.InlineObjectDeviceCounts

extension kandji_sdkAPI {

@objcMembers public class InlineObjectDeviceCounts: NSObject, Codable, JSONEncodable {

    public var total: Int?
    public var totalNum: NSNumber? {
        get {
            return total as NSNumber?
        }
    }

    public init(total: Int? = nil) {
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

}
