//
// InlineObject38.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.InlineObject38")
public typealias InlineObject38 = kandji_sdkAPI.InlineObject38

extension kandji_sdkAPI {

@objcMembers public class InlineObject38: NSObject, Codable, JSONEncodable {

    public var counts: InlineObject38Counts?
    public var limits: InlineObject38Limits?
    public var tenantOverLicenseLimit: Int?
    public var tenantOverLicenseLimitNum: NSNumber? {
        get {
            return tenantOverLicenseLimit as NSNumber?
        }
    }

    public init(counts: InlineObject38Counts? = nil, limits: InlineObject38Limits? = nil, tenantOverLicenseLimit: Int? = nil) {
        self.counts = counts
        self.limits = limits
        self.tenantOverLicenseLimit = tenantOverLicenseLimit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case counts
        case limits
        case tenantOverLicenseLimit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(counts, forKey: .counts)
        try container.encodeIfPresent(limits, forKey: .limits)
        try container.encodeIfPresent(tenantOverLicenseLimit, forKey: .tenantOverLicenseLimit)
    }
}

}
