//
// InlineObject10AutomatedDeviceEnrollment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.InlineObject10AutomatedDeviceEnrollment")
public typealias InlineObject10AutomatedDeviceEnrollment = kandji_sdkAPI.InlineObject10AutomatedDeviceEnrollment

extension kandji_sdkAPI {

@objcMembers public class InlineObject10AutomatedDeviceEnrollment: NSObject, Codable, JSONEncodable {

    public var autoEnrollEligible: Int?
    public var autoEnrollEligibleNum: NSNumber? {
        get {
            return autoEnrollEligible as NSNumber?
        }
    }
    public var autoEnrolled: Int?
    public var autoEnrolledNum: NSNumber? {
        get {
            return autoEnrolled as NSNumber?
        }
    }

    public init(autoEnrollEligible: Int? = nil, autoEnrolled: Int? = nil) {
        self.autoEnrollEligible = autoEnrollEligible
        self.autoEnrolled = autoEnrolled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case autoEnrollEligible = "auto_enroll_eligible"
        case autoEnrolled = "auto_enrolled"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(autoEnrollEligible, forKey: .autoEnrollEligible)
        try container.encodeIfPresent(autoEnrolled, forKey: .autoEnrolled)
    }
}

}
