//
// InlineObject11.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.InlineObject11")
public typealias InlineObject11 = kandji_sdkAPI.InlineObject11

extension kandji_sdkAPI {

@objcMembers public class InlineObject11: NSObject, Codable, JSONEncodable {

    public var deviceId: String?
    public var lostMode: InlineObject10LostMode?

    public init(deviceId: String? = nil, lostMode: InlineObject10LostMode? = nil) {
        self.deviceId = deviceId
        self.lostMode = lostMode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceId = "device_id"
        case lostMode = "lost_mode"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deviceId, forKey: .deviceId)
        try container.encodeIfPresent(lostMode, forKey: .lostMode)
    }
}

}
