//
// IphoneOrIpadInLostMode200ResponseUsers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.IphoneOrIpadInLostMode200ResponseUsers")
public typealias IphoneOrIpadInLostMode200ResponseUsers = kandji_sdkAPI.IphoneOrIpadInLostMode200ResponseUsers

extension kandji_sdkAPI {

@objcMembers public class IphoneOrIpadInLostMode200ResponseUsers: NSObject, Codable, JSONEncodable {

    public var regularUsers: AnyCodable?
    public var systemUsers: AnyCodable?

    public init(regularUsers: AnyCodable? = nil, systemUsers: AnyCodable? = nil) {
        self.regularUsers = regularUsers
        self.systemUsers = systemUsers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case regularUsers = "regular_users"
        case systemUsers = "system_users"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(regularUsers, forKey: .regularUsers)
        try container.encodeIfPresent(systemUsers, forKey: .systemUsers)
    }
}

}
