//
// IphoneOrIpadInLostMode200ResponseFilevault.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.IphoneOrIpadInLostMode200ResponseFilevault")
public typealias IphoneOrIpadInLostMode200ResponseFilevault = kandji_sdkAPI.IphoneOrIpadInLostMode200ResponseFilevault

extension kandji_sdkAPI {

@objcMembers public class IphoneOrIpadInLostMode200ResponseFilevault: NSObject, Codable, JSONEncodable {

    public var filevaultEnabled: AnyCodable?
    public var filevaultRecoverykeyType: String?
    public var filevaultPrkEscrowed: Int?
    public var filevaultPrkEscrowedNum: NSNumber? {
        get {
            return filevaultPrkEscrowed as NSNumber?
        }
    }
    public var filevaultNextRotation: String?
    public var filevaultRegenRequired: Int?
    public var filevaultRegenRequiredNum: NSNumber? {
        get {
            return filevaultRegenRequired as NSNumber?
        }
    }

    public init(filevaultEnabled: AnyCodable? = nil, filevaultRecoverykeyType: String? = nil, filevaultPrkEscrowed: Int? = nil, filevaultNextRotation: String? = nil, filevaultRegenRequired: Int? = nil) {
        self.filevaultEnabled = filevaultEnabled
        self.filevaultRecoverykeyType = filevaultRecoverykeyType
        self.filevaultPrkEscrowed = filevaultPrkEscrowed
        self.filevaultNextRotation = filevaultNextRotation
        self.filevaultRegenRequired = filevaultRegenRequired
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case filevaultEnabled = "filevault_enabled"
        case filevaultRecoverykeyType = "filevault_recoverykey_type"
        case filevaultPrkEscrowed = "filevault_prk_escrowed"
        case filevaultNextRotation = "filevault_next_rotation"
        case filevaultRegenRequired = "filevault_regen_required"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(filevaultEnabled, forKey: .filevaultEnabled)
        try container.encodeIfPresent(filevaultRecoverykeyType, forKey: .filevaultRecoverykeyType)
        try container.encodeIfPresent(filevaultPrkEscrowed, forKey: .filevaultPrkEscrowed)
        try container.encodeIfPresent(filevaultNextRotation, forKey: .filevaultNextRotation)
        try container.encodeIfPresent(filevaultRegenRequired, forKey: .filevaultRegenRequired)
    }
}

}
