//
// PrismRequestCategoryExport400Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.PrismRequestCategoryExport400Response")
public typealias PrismRequestCategoryExport400Response = kandji_sdkAPI.PrismRequestCategoryExport400Response

extension kandji_sdkAPI {

@objcMembers public class PrismRequestCategoryExport400Response: NSObject, Codable, JSONEncodable {

    public var detail: String?

    public init(detail: String? = nil) {
        self.detail = detail
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case detail
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(detail, forKey: .detail)
    }
}

}
