//
// SettingsLicensing200ResponseLimits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.SettingsLicensing200ResponseLimits")
public typealias SettingsLicensing200ResponseLimits = kandji_sdkAPI.SettingsLicensing200ResponseLimits

extension kandji_sdkAPI {

@objcMembers public class SettingsLicensing200ResponseLimits: NSObject, Codable, JSONEncodable {

    public var maxDevices: Int?
    public var maxDevicesNum: NSNumber? {
        get {
            return maxDevices as NSNumber?
        }
    }
    public var maxDevicesPerPlatform: SettingsLicensing200ResponseLimitsMaxDevicesPerPlatform?
    public var planType: String?

    public init(maxDevices: Int? = nil, maxDevicesPerPlatform: SettingsLicensing200ResponseLimitsMaxDevicesPerPlatform? = nil, planType: String? = nil) {
        self.maxDevices = maxDevices
        self.maxDevicesPerPlatform = maxDevicesPerPlatform
        self.planType = planType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxDevices = "max_devices"
        case maxDevicesPerPlatform = "max_devices_per_platform"
        case planType = "plan_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxDevices, forKey: .maxDevices)
        try container.encodeIfPresent(maxDevicesPerPlatform, forKey: .maxDevicesPerPlatform)
        try container.encodeIfPresent(planType, forKey: .planType)
    }
}

}
