//
// Success200Response8.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.Success200Response8")
public typealias Success200Response8 = kandji_sdkAPI.Success200Response8

extension kandji_sdkAPI {

@objcMembers public class Success200Response8: NSObject, Codable, JSONEncodable {

    public var recoveryPassword: String?

    public init(recoveryPassword: String? = nil) {
        self.recoveryPassword = recoveryPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recoveryPassword = "recovery_password"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(recoveryPassword, forKey: .recoveryPassword)
    }
}

}
