//
// Success201Response1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.Success201Response1")
public typealias Success201Response1 = kandji_sdkAPI.Success201Response1

extension kandji_sdkAPI {

@objcMembers public class Success201Response1: NSObject, Codable, JSONEncodable {

    public var _id: String?
    public var name: String?

    public init(_id: String? = nil, name: String? = nil) {
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_id, forKey: ._id)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

}

@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension kandji_sdkAPI.Success201Response1: Identifiable {}
