//
// Success200Response17.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.Success200Response17")
public typealias Success200Response17 = kandji_sdkAPI.Success200Response17

extension kandji_sdkAPI {

@objcMembers public class Success200Response17: NSObject, Codable, JSONEncodable {

    public var counts: Success200Response17Counts?
    public var limits: Success200Response17Limits?
    public var tenantOverLicenseLimit: Int?
    public var tenantOverLicenseLimitNum: NSNumber? {
        get {
            return tenantOverLicenseLimit as NSNumber?
        }
    }

    public init(counts: Success200Response17Counts? = nil, limits: Success200Response17Limits? = nil, tenantOverLicenseLimit: Int? = nil) {
        self.counts = counts
        self.limits = limits
        self.tenantOverLicenseLimit = tenantOverLicenseLimit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case counts
        case limits
        case tenantOverLicenseLimit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(counts, forKey: .counts)
        try container.encodeIfPresent(limits, forKey: .limits)
        try container.encodeIfPresent(tenantOverLicenseLimit, forKey: .tenantOverLicenseLimit)
    }
}

}
