//
// Success200Response6.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.Success200Response6")
public typealias Success200Response6 = kandji_sdkAPI.Success200Response6

extension kandji_sdkAPI {

@objcMembers public class Success200Response6: NSObject, Codable, JSONEncodable {

    public var key: String?

    public init(key: String? = nil) {
        self.key = key
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(key, forKey: .key)
    }
}

}
