//
// Success200Response17Limits.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.Success200Response17Limits")
public typealias Success200Response17Limits = kandji_sdkAPI.Success200Response17Limits

extension kandji_sdkAPI {

@objcMembers public class Success200Response17Limits: NSObject, Codable, JSONEncodable {

    public var planType: String?
    public var maxDevices: Int?
    public var maxDevicesNum: NSNumber? {
        get {
            return maxDevices as NSNumber?
        }
    }
    public var maxDevicesPerPlatform: Success200Response17LimitsMaxDevicesPerPlatform?

    public init(planType: String? = nil, maxDevices: Int? = nil, maxDevicesPerPlatform: Success200Response17LimitsMaxDevicesPerPlatform? = nil) {
        self.planType = planType
        self.maxDevices = maxDevices
        self.maxDevicesPerPlatform = maxDevicesPerPlatform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case planType = "plan_type"
        case maxDevices = "max_devices"
        case maxDevicesPerPlatform = "max_devices_per_platform"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(planType, forKey: .planType)
        try container.encodeIfPresent(maxDevices, forKey: .maxDevices)
        try container.encodeIfPresent(maxDevicesPerPlatform, forKey: .maxDevicesPerPlatform)
    }
}

}
