//
// VulnerabilitiesListVulnerabilities200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

@available(*, deprecated, renamed: "kandji_sdkAPI.VulnerabilitiesListVulnerabilities200Response")
public typealias VulnerabilitiesListVulnerabilities200Response = kandji_sdkAPI.VulnerabilitiesListVulnerabilities200Response

extension kandji_sdkAPI {

@objcMembers public class VulnerabilitiesListVulnerabilities200Response: NSObject, Codable, JSONEncodable {

    public var results: AnyCodable?
    public var size: Int?
    public var sizeNum: NSNumber? {
        get {
            return size as NSNumber?
        }
    }
    public var total: Int?
    public var totalNum: NSNumber? {
        get {
            return total as NSNumber?
        }
    }

    public init(results: AnyCodable? = nil, size: Int? = nil, total: Int? = nil) {
        self.results = results
        self.size = size
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case results
        case size
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(results, forKey: .results)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(total, forKey: .total)
    }
}

}
